<?php

/**
 * @file
 * Contains admin_dashboard.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function admin_dashboard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the admin_dashboard module.
    case 'help.page.admin_dashboard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cypress Admin Dashboard') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function admin_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'cypress_admin_dashboard' => [
      'variables' => [
        'configuration' => NULL,
      ],
      'template' => 'cypress-admin-dashboard',
    ],
  ];
}
