cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://cypressextdev2.prod.acquia-sites.com/themes/cypress_store/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  cypress_store: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://CYPRESS_LOGO_2017_RGB_249x78px_0.png'
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
