<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\commerce_order\Entity\OrderItem;
use Drupal\commerce_product\Entity\Product;
use Drupal\commerce_shipping\Entity\ShippingMethod;



/**
 * Implements form_alter().
 */
function cypress_custom_address_form_alter(&$form, $form_state, $form_id)
{
  $order = \Drupal::service('commerce_cart.cart_provider')->getCartIds();
  $order_id = $order['0'];
  if ($form_id == 'views_form_commerce_cart_form_default_' . $order_id) {
    array_unshift($form['actions']['checkout']['#submit'], 'anonymous_checkout_flow');
  }
}

// anonymous cart submit sunction
function anonymous_checkout_flow()
{

  if (\Drupal::currentUser()->isAnonymous()) {
    $response = new RedirectResponse('/saml_login');
    return $response->send();
  }

}

/**
 * Shipping Rules For Cypress Store.
 * Implements hook_commerce_shipping_methods_alter().
 */
function cypress_custom_address_commerce_shipping_methods_alter(&$shipping_methods, $shipment) {

  // Get Shipping Profile to get fetch the Address domestic and international.
  $shipment_profile = $shipment->getShippingProfile();
  $shipping_address = $shipment->getShippingProfile()
    ->get('field_contact_address')
    ->getValue();
  $shipping_country_code = $shipping_address[0]['country_code'];
  // Get the product type from order item.
  $shipment_order_item = $shipment->getItems();
  $order_item_id = $shipment_order_item[0]->getOrderItemId();
  $order_item = OrderItem::load($order_item_id);
  $product_variation = $order_item->getPurchasedEntity();
  if (!empty($product_variation)) {
    $product_id = $product_variation->get('product_id')
      ->getValue()[0]['target_id'];
    if (!empty($product_id)) {
      $product = Product::load($product_id);
      $product_type = $product->get('type')->getValue()[0]['target_id'];
    }
    if ($product_type == 'default') {
      if ($shipping_country_code == "US") {
        foreach ($shipping_methods as $key => $shipping_method) {
          $shipping_method_name = $shipping_method->getName();
          $shipping_method_id = $shipping_method->id();
          if (!($shipping_method_name == 'USA - FedEx Express Saver For Kit Domestic') && !($shipping_method_name == 'USA FedEx Standard Overnight For Sample CAT_A')){
            unset($shipping_methods[$key]);
          }
        }
      }
      else {
        foreach ($shipping_methods as $key => $shipping_method) {
          $shipping_method_name = $shipping_method->getName();
          $shipping_method_id = $shipping_method->id();
          if (!($shipping_method_name == 'FedEx International Economy For Kits') && !($shipping_method_name == 'FedEx International Priority For Kits')){
            unset($shipping_methods[$key]);
          }
        }
      }
    }
    elseif ($product_type == 'part') {
      $can_sample = $product->get('field_can_sample')
        ->getValue()[0]['value'];
      // CAT_A products.
      if ($can_sample == 1) {
        if ($shipping_country_code == 'US'){
          foreach ($shipping_methods as $key => $shipping_method) {
            $shipping_method_name = $shipping_method->getName();
            $shipping_method_id = $shipping_method->id();
            if (!($shipping_method_name == 'USA FedEx 2Day For Sample CAT_A') && !($shipping_method_name == 'USA FedEx Standard Overnight For Sample CAT_A')){
              unset($shipping_methods[$key]);
            }
          }
        }
        else {
          foreach ($shipping_methods as $key => $shipping_method) {
            $shipping_method_name = $shipping_method->getName();
            $shipping_method_id = $shipping_method->id();
            if (!($shipping_method_name == 'FedEx International Economy For Sample CAT_A') && !($shipping_method_name == 'FedEx International Priority For Sample CAT_A')){
              unset($shipping_methods[$key]);
            }
          }
        }
      }
      elseif ($can_sample == 2) {
        if ($shipping_country_code == 'US'){
          foreach ($shipping_methods as $key => $shipping_method) {
            $shipping_method_name = $shipping_method->getName();
            $shipping_method_id = $shipping_method->id();
            if (!($shipping_method_name == 'USA FedEx 2Day For Sample CAT_B') && !($shipping_method_name == 'USA FedEx Standard Overnight For Sample CAT_B')){
              unset($shipping_methods[$key]);
            }
          }
        }
        else {
          foreach ($shipping_methods as $key => $shipping_method) {
            $shipping_method_name = $shipping_method->getName();
            $shipping_method_id = $shipping_method->id();
            if (!($shipping_method_name == 'FedEx International Economy For Sample CAT_B') && !($shipping_method_name == 'FedEx International Priority For Sample CAT_B')){
              unset($shipping_methods[$key]);
            }
          }
        }
      }
    }
  }
}

