<?php

/**
 * @file
 * Contains file_download_tracker.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file_download_tracker\FileDownloadTracker;

/**
 * Implements hook_help().
 */
function file_download_tracker_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the file_download_tracker module.
    case 'help.page.file_download_tracker':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('File downloads tracker') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_file_transfer().
 */
function file_download_tracker_file_transfer($uri, array $headers) {
  $current_uri = \Drupal::request()->getRequestUri();
  $exp = explode("/", $current_uri);
  $fid = array($exp[2]);
  // load the Symfony event dispatcher object through services
  $dispatcher = \Drupal::service('event_dispatcher');
  // creating our event class object.
  $event = new FileDownloadTracker($fid);
  // dispatching the event through the ‘dispatch’  method,
  // passing event name and event object ‘$event’ as parameters.
  $dispatcher->dispatch(FileDownloadTracker::SUBMIT, $event);
}
