<?php

define("AVNET", '\Drupal\cypress_store_vendor\Avnet');
define("DIGIKEY", '\Drupal\cypress_store_vendor\Digikey');

use Drupal\cypress_store_vendor\Vendor\Avnet;

/**
 * Implements hook_mail().
 */
function cypress_store_vendor_mail($key, &$message, $params) {
$options = array(
  'langcode' => $message['langcode'],
);
 switch ($key) {
   case 'logger':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('logger: @title', array('@title' => $params['title']), $options);
     $message['body'][] = $params['message'];
     break;
 }
}

/**
 * Implements hook_cron().
 *
 * Cron to update Avnet inventory details.
 */
function cypress_store_vendor_cron() {
  $avnet_handler = new Avnet();
  $avnet_handler->updateInventory();
}
