dblog_filter.settings:
  type: config_object
  label: 'DB Log Filter'
  mapping:
    severity_levels:
      type: sequence
      label: 'Log according to Severity levels'
      sequence:
        type: string
        label: 'Severity Levels'
    log_values:
      type: string
      label: 'Custom Logging'
